[package]
name = "openloader"
version = "0.1.0"
edition = "2024"

[dependencies]
derive-ctor = "1.0.6"
derive_more = { version = "2.1.1", features = ["is_variant"], default-features = false }
ufmt = "0.2.0"
